.PHONY:	 all up fclean

all:
		@sudo docker-compose -f srcs/docker-compose.yml up --build -d

up:					
		@sudo docker-compose -f srcs/docker-compose.yml up --build -d

fclean:	
		@sudo docker-compose -f srcs/docker-compose.yml down